export const GET_USER = 'GET_USER';
export const GET_USER_BY_ID = 'GET_USER_BY_ID';
export const CLEAR_USERS_STATE = 'CLEAR_USERS_STATE';
export const CLEAR_PROFILE_STATE = 'CLEAR_PROFILE_STATE';
export const SEARCH_BY_NAME = 'SEARCH_BY_NAME';
